name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install rzup
        run: |
          curl -L https://risczero.com/install | bash
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH
      - name: Install RISC Zero toolchain
        run: rzup install rust && rzup install cargo-risczero 1.2.6
      - run: cargo build --release
      - run: cargo test
